import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
food_quality = ctrl.Antecedent(np.arange(0, 101, 1), "food_quality")
serve = ctrl.Antecedent(np.arange(0, 101, 1), "serve")
tip = ctrl.Consequent(np.arange(0, 26, 1), "tip")
food_quality["bad"] = fuzz.trimf(food_quality.universe, [0, 28, 55])
food_quality["fair"] = fuzz.trimf(food_quality.universe, [40, 63, 85])
food_quality["good"] = fuzz.trimf(food_quality.universe, [75, 88, 101])
serve["bad"] = fuzz.trimf(serve.universe, [0, 0, 50])
serve["fair"] = fuzz.trimf(serve.universe, [40, 60, 80])
serve["good"] = fuzz.trimf(serve.universe, [70, 85, 101])   
tip["low"] = fuzz.trimf(tip.universe, [0, 0, 13])
tip["mid"] = fuzz.trimf(tip.universe, [0, 13, 26])
tip["high"] = fuzz.trimf(tip.universe, [13, 26, 26])
rule1 = ctrl.Rule(serve["bad"] and food_quality["bad"]  , tip["low"])
rule2 = ctrl.Rule( food_quality["fair"] and serve["bad"], tip["low"])
rule3 = ctrl.Rule( food_quality["good"] and serve["bad"] , tip["mid"])
rule4 = ctrl.Rule(  food_quality["bad"] and serve["fair"],  tip["low"])
rule5 = ctrl.Rule(   food_quality["fair"] and serve["fair"] , tip["mid"])
rule6 = ctrl.Rule(  food_quality["good"] and serve["fair"] , tip["mid"])
rule7 = ctrl.Rule(  food_quality["bad"] and serve["good"] , tip["mid"])
rule8 = ctrl.Rule(  food_quality["fair"]and serve["good"] , tip["high"])
rule9 = ctrl.Rule(  food_quality["good"] and serve["good"]  , tip["high"])
tip_f = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9])
tipss= ctrl.ControlSystemSimulation(tip_f)
tipss.input["food_quality"] = int(input("Lütfen yemeğin kalitesini maximum 100 minimum 0 olacak şekilde puanlayın: "))
tipss.input["serve"] = int(input("Lütfen servis kalitesini maximum 100 minimum 0 olacak şekilde puanlayın: "))
Hesap= int(input("Ödenecek hesap tutarı: "))
tipss.compute()
print("Ödenecek bahşiş tutarı %",tipss.output["tip"])
print("Verilecek bahşiş tutarı: ", round(Hesap*round(tipss.output["tip"])/100)," TL")
tip.view(sim=tipss)

